version: "3"
services:
  product:
    image: pagonxt/product
    build: product
    entrypoint: 'npm run start:dev'
    volumes:
      - ./product:/app
    ports:
      - 3000:3000
  product_db:
    image: mysql
    container_name: product_db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=product
      - MYSQL_USER=thais
      - MYSQL_PASSWORD=040294
    ports: 
      - 3306:3306
  account:
    image: pagonxt/account
    build: account
    entrypoint: 'npm run start:dev'
    volumes:
      - ./account:/app
    ports:
      - 3001:3000
  account-database:
    image: mongo
    container_name: account-database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=account
    ports:
      - 27017:27017