version: "3"
services:
  product:
    image: pagonxt/product
    build: product
    ports:
      - 3001:3000
  account:
    image: pagonxt/account
    build: account
    ports:
      - 3000:3000
  account-database:
    image: mongo
    container_name: account-database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=account
    ports:
      - 27017:27017
